version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis-server
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
  redis-server:
    image: "redis"
