version: '3.7'  # It's good practice to specify a more specific version if not the latest

services:

  redis-server:
    image: "redis"
    ports:
      - "6379:6379"
    networks:
      - app-network
      
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis-server
    networks:
      - app-network
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379


networks:
  app-network:
    driver: bridge
